### ISSUE TITLE
[QST] Can CUTLASS be used for non-gemm kernels

### ISSUE THREAD

**Issue by mgrabban** [codeplaysoftware/cutlass-fork#101]
Hello,
I think it is obvious that focus of CUTLASS is GEMM (and CONV) along with Epilogue fusion. But is it still possible / advisable to use it for non-GEMM kernels, such as for implementing a pure activation function, or a normalization function (layernorm, rmsnorm) etc.?
Thanks.

**Comment by aacostadiaz** [comment]
Cutlass is for linear algebra and can be used to implement non-GEMM kernels. You can find some examples in the `example` folder. You can also check the `tools` folder for layernorm and other implementations, although these are not implemented using cutlass 3 components.

**Comment by mgrabban** [comment]
Thanks for pointing out layernorm in `tools` folder but it seems CUTLASS is not appropriate for non-GEMM ops.

In `examples` folder, I could not find standalone non-GEMM kernels. Obviously there are element-wise ops (e.g. relu) that are fused to GEMM. I also say GEMM-layernorm-GEMM but again this is not standalone.
In `tools` folder, the layernorm /rmsnorm kernels are really pure cuda kernels; only the launcher supports CUTLASS tensors (they are simply cast to datatype supported by the cuda kernel).
